# Generated by Django 5.1.1 on 2024-10-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursevideo_enrolledcourse_coursenote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='video_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
