# Generated by Django 5.1.1 on 2024-10-08 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursevideo_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='enrolled_courses',
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
