# Generated by Django 5.1.1 on 2024-10-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_members_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='enrolled_courses',
        ),
        migrations.AddField(
            model_name='members',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, to='course.enrolledcourse'),
        ),
    ]
