# Generated by Django 5.1.1 on 2024-10-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_enrolledcourse_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, null=True, to='course.enrolledcourse'),
        ),
    ]
