# Generated by Django 5.1.1 on 2024-10-09 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_members_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursenote',
            name='video',
        ),
        migrations.RemoveField(
            model_name='members',
            name='enrolled_courses',
        ),
        migrations.AddField(
            model_name='coursenote',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursenote',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CourseVideo',
        ),
    ]
