# Generated by Django 5.1.1 on 2024-10-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_enrolled_courses_enrolledcourse_user_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='user_enrolled',
            new_name='enrolled_courses',
        ),
    ]
