# Generated by Django 5.1.1 on 2024-10-09 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_user_enrolled_enrolledcourse_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='enrolled_courses',
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='enrolled_courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
