# Generated by Django 5.1.1 on 2024-10-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_enrolledcourse_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='enrolled_courses',
            new_name='enrolled_users',
        ),
    ]
