# Generated by Django 5.1.1 on 2024-10-09 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_rename_enrolled_courses_enrolledcourse_enrolled_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursenote',
            name='video_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coursenote',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
