# Generated by Django 5.1.1 on 2024-10-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_coursenote_video_id_alter_coursenote_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursenote',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.enrolledcourse'),
        ),
    ]
