# Generated by Django 5.1.1 on 2024-10-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_coursenote_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursenote',
            name='course_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
